### ISSUE TITLE
nimsuggest needs a flag to specify the compiler dir

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/nimsuggest#6]
Should fix things like copying it over to `bin/nimsuggest` in the compiler dir and stdlib files not found.

**Comment by dom96** [comment]
The compiler dir? Why does it need the compiler dir? Surely you mean the lib dir? If so, then NimSuggest needs to find the lib dir itself, it's not hard.

**Comment by reactormonk** [comment]
Yeah, lib dir would work too. And how would you find it?

**Comment by dom96** [comment]
``findExe("nim").parentDir() / "lib"``, then you need to handle the cases where Nim is installed into ``/usr/lib`` (or wherever) but maybe then the compiler already has logic for that which you can copy.

**Comment by reactormonk** [comment]
I am pretty sure debian's gonna hate us for that.

**Comment by pigmej** [comment]
@dom96 it crashes when you have `nim` executable as symlink. I think it should follow symlinks.

**Comment by nordborn** [comment]
Hello! With nim 0.11.2 got error message from nimble "Unsatisfied dependency: nim (>= 0.11.3)" But where is nim 0.11.3? Got error while dowloading it: got nim 0.10.3 instead of 0.11.3 with broken /compiler/nimsuggest (message "was moved.." insiide). When I was tring to compile under 0.11.2 got this msg: "compiler/nimsuggest/sexp.nim(469, 26) Error: undeclared identifier: 'Hash'". What should I do? Thanks

**Comment by reactormonk** [comment]
@nordborn unrelated issue. Try the devel compiler.

**Comment by filcuc** [comment]
on my machine i get 
Error cannot open /usr/local/lib/nim/system.nim'

My nim compiler is build from source in my home directory. I than use a symlink from /usr/local/bin/nim to point to my /home/user/Repo/nim/bin/nim executable

**Comment by reactormonk** [comment]
Yeah, the compiler itself follows symlinks, whereas nimsuggest does not (yet).

**Comment by filcuc** [comment]
I tried to fix it myself but the OS module lacks of a readLink python equivalent function. Do you think that's better to add such functionality and or add an explicit command flag?

**Comment by reactormonk** [comment]
Try this code: https://github.com/nim-lang/Nim/blob/devel/lib/pure/os.nim#L1746-L1753

**Comment by dom96** [comment]
Let's not add an explicit flag please.

**Comment by reactormonk** [comment]
Ok.

**Comment by filcuc** [comment]
I agree, i will fix this and maybe export that function in the OS module as readLink. I checked python and is available only on unix. So we can do the same

**Comment by reactormonk** [comment]
I'd say make readlink a noop if it's on non-posix systems, so it's less complicated to use.

**Comment by Varriount** [comment]
Wait, why is readlink required? Shouldn't nimsuggest automatically follow the target of the symlink?

**Comment by filcuc** [comment]
@varriount well obviously we can copy and paste that function and fix it here. However to me having a readLink proc seems a pretty standard requirement on unix. Am i wrong? You say that we should also support that on windows and i agree. However in python they added support for windows since python 3.2. My idea was to start initially with a unix only implementation. Keep in mind that this is my first i try to contribute to nim so i don't know if having platform specific functions in a module could be accepted.

**Comment by Varriount** [comment]
@filcuc if you open a PR with the Unix implementation, I can add the Windows implementation.

**Comment by filcuc** [comment]
@varriount ok
